name: ffbeequip
description: Creating a mobile implementation of the popular FFBEequip site

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/data/
  - assets/images/units/


